package rules.rulesHello
import com.rule.drools.pojo.Person;
    rule "test001"
        when
            eval(true)
        then
            System.out.println("hello world");
    end

    rule "test002"
        when
         $p:Person();
        then
         System.out.println("输入引用对象："+$p);
    end

    rule "test003"
        when
            $p:Person(name=="张三",age==30);
        then
            $p.setAge(40);
            System.out.println("输出传入参数有一个张三，年龄30的");
    end

    rule "test004"
        when
            $p:Person(name=="张三",age==30);
        then
            $p.setAge(40);
            update($p);
            System.out.println("将30岁的张三改为40");
     end

    rule "test005"
        when
            $p:Person(name=="张三",age==40);
        then
            System.out.println("规则005成功");
      end

    rule "test006"
         when
             $p:Person(age/2==20);
         then
             System.out.println("规则006成功"+$p);
    end
    rule "test007"
          when
              $p:Person((age%2)==0);
          then
              System.out.println("规则007成功"+$p);
     end