package com.newcore.ifrs17.fact.cashflow;
import  com.newcore.ifrs17.fact.cashflow.IFRS17DefActualCashflowUniDebitOrCredit;

rule "IIFRS17DefActualCashflowUniDebitOrCredit_dataSource_check"
    when ifrs17DefActualCashflowUniDebitOrCredit:IFRS17DefActualCashflowUniDebitOrCredit( dataSource==null || dataSource not matches "^[A-Z0-9a-z]{1,100}$")
    then
        ifrs17DefActualCashflowUniDebitOrCredit.setRemark(ifrs17DefActualCashflowUniDebitOrCredit.getRemark()==null?"业务系统代码为空或不符合规则 \n":ifrs17DefActualCashflowUniDebitOrCredit.getRemark()+"业务系统代码为空或不符合规则 \n");

    end
rule "IIFRS17DefActualCashflowUniDebitOrCredit_transCode_checkNULL"
    when ifrs17DefActualCashflowUniDebitOrCredit:IFRS17DefActualCashflowUniDebitOrCredit( transCode==null || transCode not matches "^[A-Z0-9a-z]{2}$")
    then
        ifrs17DefActualCashflowUniDebitOrCredit.setRemark(ifrs17DefActualCashflowUniDebitOrCredit.getRemark()==null?"收付费项目为空或不符合规则 \n":ifrs17DefActualCashflowUniDebitOrCredit.getRemark()+"收付费项目为空或不符合规则 \n");
    end

rule "IIFRS17DefActualCashflowUniDebitOrCredit_transType_check"
    when ifrs17DefActualCashflowUniDebitOrCredit:IFRS17DefActualCashflowUniDebitOrCredit(transType == null || transType not in ("1","2","3","4"))
    then
        ifrs17DefActualCashflowUniDebitOrCredit.setRemark(ifrs17DefActualCashflowUniDebitOrCredit.getRemark()==null?"业务类别不可为空或不符合规则":ifrs17DefActualCashflowUniDebitOrCredit.getRemark()+"业务类别不可为空或不符合规则 \n");
    end

rule "IIFRS17DefActualCashflowUniDebitOrCredit_payType_check"
    when ifrs17DefActualCashflowUniDebitOrCredit:IFRS17DefActualCashflowUniDebitOrCredit(payType == null || (payType not matches"^[A-Za-z]{1,100}$" && payType not matches "^[A-Za-z0-9]{1,100}$"))
    then
        ifrs17DefActualCashflowUniDebitOrCredit.setRemark(ifrs17DefActualCashflowUniDebitOrCredit.getRemark()==null?"收付款方式为空或不符合规则":ifrs17DefActualCashflowUniDebitOrCredit.getRemark()+"收付款方式为空或不符合规则 \n");
    end


rule "IIFRS17DefActualCashflowUniDebitOrCredit_riskType_check"
    when ifrs17DefActualCashflowUniDebitOrCredit:IFRS17DefActualCashflowUniDebitOrCredit( riskType==null || riskType not in ("1","9"))
    then
        ifrs17DefActualCashflowUniDebitOrCredit.setRemark(ifrs17DefActualCashflowUniDebitOrCredit.getRemark()==null?"长短险标志为空或不符合规则 \n":ifrs17DefActualCashflowUniDebitOrCredit.getRemark()+"长短险标志为空或不符合规则 \n");
    end

rule "IIFRS17DefActualCashflowUniDebitOrCredit_typeCys_checkNULL"
    when ifrs17DefActualCashflowUniDebitOrCredit:IFRS17DefActualCashflowUniDebitOrCredit( flagCys == null || flagCys not in ("1","0"))
    then
        ifrs17DefActualCashflowUniDebitOrCredit.setRemark(ifrs17DefActualCashflowUniDebitOrCredit.getRemark()==null?"冲应收标识不可为空或不符合规则":ifrs17DefActualCashflowUniDebitOrCredit.getRemark()+"冲应收标识不可为空或不符合规则 \n");
    end


rule "IIFRS17DefActualCashflowUniDebitOrCredit_accFlag_check"
    when ifrs17DefActualCashflowUniDebitOrCredit:IFRS17DefActualCashflowUniDebitOrCredit(accFlag == null || accFlag not in ("1","0","2"))
    then
        ifrs17DefActualCashflowUniDebitOrCredit.setRemark(ifrs17DefActualCashflowUniDebitOrCredit.getRemark()==null?"到账确认标识为空或不符合规则":ifrs17DefActualCashflowUniDebitOrCredit.getRemark()+"到账确认标识为空或不符合规则 \n");
    end

rule "IIFRS17DefActualCashflowUniDebitOrCredit_direction_check"
    when ifrs17DefActualCashflowUniDebitOrCredit:IFRS17DefActualCashflowUniDebitOrCredit(direction == null)
    then
        ifrs17DefActualCashflowUniDebitOrCredit.setRemark(ifrs17DefActualCashflowUniDebitOrCredit.getRemark()==null?"借贷方向不可为空":ifrs17DefActualCashflowUniDebitOrCredit.getRemark()+"借贷方向不可为空 \n");
    end

