package com.newcore.ifrs17.fact.contract;
import  com.newcore.ifrs17.fact.contract.IFRS17DefContrgrpVirtualAccount;

rule "IFRS17DefContrgrpVirtualAccount_polCode_check"
    when ifrs1717DefContrgrpVirtualAccount:IFRS17DefContrgrpVirtualAccount( polCode==null || polCode.trim() == "" || polCode.toUpperCase() =="NULL"|| polCode not matches("^[A-Za-z0-9_]*$"))
    then
        ifrs1717DefContrgrpVirtualAccount.setRemark("险种代码为空或不符合规则 \n");
    end
rule "IFRS17DefContrgrpVirtualAccount_isNeedGroupcap_check"
    when ifrs1717DefContrgrpVirtualAccount:IFRS17DefContrgrpVirtualAccount(isNeedGroupcap == null || isNeedGroupcap not in ("Y","N"))
    then
        ifrs1717DefContrgrpVirtualAccount.setRemark(ifrs1717DefContrgrpVirtualAccount.getRemark()==null?"是否需要生成团帽单不可为空或不符合规则 \n":ifrs1717DefContrgrpVirtualAccount.getRemark()+"是否需要生成团帽单不可为空或不符合规则 \n");
    end
rule "IFRS17DefContrgrpVirtualAccount_polName_check"
    when ifrs1717DefContrgrpVirtualAccount:IFRS17DefContrgrpVirtualAccount(polName != null && polName.trim() == "")
    then
        ifrs1717DefContrgrpVirtualAccount.setRemark(ifrs1717DefContrgrpVirtualAccount.getRemark()==null?"险种名称不可为空 \n":ifrs1717DefContrgrpVirtualAccount.getRemark()+"险种名称不可为空 \n");
    end